### ISSUE TITLE
npm module draggabilly cannot find eventie

### ISSUE THREAD

**Issue by Schnueggel** [doroppu/yoso-starter-app#2]
Hi,

I installed npm module draggabilly and required it in the app.

I get the following errormessage:

**Cannot find module 'eventie' from '/Users/christiansteinmann/PhpstormProjects/book-insights/node_modules/draggabilly/node_modules/unidragger'**

I think the problem is more related to the submodule unidragger it requires the module eventie but does  not have the direct dependency to it. Instead it seems to rely on its dependency unipointer which includes eventie. 

* draggabilly
    * node_modules
        * unidragger // require('eventie') is used on this level
            * node_modules
                 * unipointer 
                     * node_modules
                          * eventie

**Comment by lukas-zech-software** [comment]
Yup, definitly missing dependency in the unidragger module
https://github.com/metafizzy/unidragger/blob/master/package.json does not define a dependency to **eventie** although it is required in its code

I suggest opening an issue [there](https://github.com/metafizzy/unidragger/issues)
